Repository surendratalk/awesome-github-profiles, pull requests merged in 2022-10, with the labels that each got.

#2 Create protonkishan.json
  protonkishan.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1 Create techpangaa.json
  techpangaa.json
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#3 Create truekishan.json
  truekishan.json
Labels: help wanted, hacktoberfest, hacktoberfest-accepted

#5 Create awesometitle.json
  awesometitle.json
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#6 Create imagithubuserr.json
  imagithubuserr.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 fix: add priyansh2998.json
  priyansh2998.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 Charalambos
  CharalambosIoannou.json
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create MERITARAFSE.json
  MERITARAFSE.json
Labels: hacktoberfest, hacktoberfest-accepted

#14 fix: add YashIndane
  YashIndane.json
Labels: hacktoberfest, hacktoberfest-accepted
